language: csharp
solution: Tinify.sln
matrix:
  include:
  - mono: 3.8
  - mono: 3.10
  - mono: 3.12
  - mono: 4.0
  - mono: 4.2
  - mono: 4.4
  - mono: 4.6
  - mono: latest
  - dotnet: 1.0.0-preview2-003131
    mono: none
    env: DOTNETCORE=1
