version: '{build}'

pull_requests:
  do_not_increment_build_number: true

branches:  
  only:
  - master

configuration: Release

environment:
  TINIFY_KEY:
    secure: ZF/29NnonLrQuvAfRbhotwBPdrvQ+D+ayXVxWji8HaLYKSV2WH5kTDJSGSfB4j7S

build_script:
- ps: .\Build.ps1

test: off  

nuget:
  disable_publish_on_pr: true

artifacts:
- path: artifacts\**\*.nupkg
  name: NuGet

deploy:
- provider: NuGet
  name: ci
  server: https://www.myget.org/F/tinify/api/v2/package
  api_key:
    secure: FttMSHHG5qxUgCRKjnGtl2SZQCVEg+gIYoS+lJaEDkdBFjtxTU2b2WnX3DDGBQ1J
  skip_symbols: true
  on:
    branch: master
- provider: NuGet
  name: production
  api_key:
    secure: live_encrypted_key_here
  on:
    branch: master
    appveyor_repo_tag: true